//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_AppAuthor
    {
        public int AppId { get; set; }
        public string AppSecret { get; set; }
        public string SafeCode { get; set; }
        public string AuthorType { get; set; }
        public string Remarks { get; set; }
    }
}
