//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center_Server
    {
        public string ProjectName { get; set; }
        public string PublicIP { get; set; }
        public string RunTime { get; set; }
        public Nullable<int> RegisterTime { get; set; }
        public Nullable<int> RTUCount { get; set; }
        public Nullable<System.DateTime> DTime { get; set; }
        public string RunState { get; set; }
        public Nullable<System.DateTime> SrartTime { get; set; }
        public string IP { get; set; }
    }
}
