//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementsChartsInfo_Tab
    {
        public string ItemID { get; set; }
        public Nullable<decimal> DisplayAreaMax { get; set; }
        public Nullable<decimal> DisplayAreaMin { get; set; }
        public Nullable<decimal> AlarmAreaMax { get; set; }
        public Nullable<decimal> AlarmAreaMin { get; set; }
    }
}
