//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocaInfo_Tab
    {
        public string STCD { get; set; }
        public string LocaManager { get; set; }
        public string Tel { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Altitude { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string Describe { get; set; }
    }
}
