//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MonitorManagerEntities : DbContext
    {
        public MonitorManagerEntities()
            : base("name=MonitorManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<B_AppAuthor> B_AppAuthor { get; set; }
        public virtual DbSet<B_TbButton> B_TbButton { get; set; }
        public virtual DbSet<B_TbIcon> B_TbIcon { get; set; }
        public virtual DbSet<B_TbMenu> B_TbMenu { get; set; }
        public virtual DbSet<B_TbMenuButton> B_TbMenuButton { get; set; }
        public virtual DbSet<B_TbRole> B_TbRole { get; set; }
        public virtual DbSet<B_TbRoleMenu> B_TbRoleMenu { get; set; }
        public virtual DbSet<B_TbRoleMenuButton> B_TbRoleMenuButton { get; set; }
        public virtual DbSet<B_TbUser> B_TbUser { get; set; }
        public virtual DbSet<B_TbUserRole> B_TbUserRole { get; set; }
        public virtual DbSet<Center_RTUChange> Center_RTUChange { get; set; }
        public virtual DbSet<Center_Server> Center_Server { get; set; }
        public virtual DbSet<Center_StartState> Center_StartState { get; set; }
        public virtual DbSet<ElementsChartsInfo_Tab> ElementsChartsInfo_Tab { get; set; }
        public virtual DbSet<LocaInfo_Tab> LocaInfo_Tab { get; set; }
        public virtual DbSet<YY_COMMAND_TEMP> YY_COMMAND_TEMP { get; set; }
        public virtual DbSet<YY_DATA_AUTO> YY_DATA_AUTO { get; set; }
        public virtual DbSet<YY_DATA_COMMAND> YY_DATA_COMMAND { get; set; }
        public virtual DbSet<YY_DATA_GPS> YY_DATA_GPS { get; set; }
        public virtual DbSet<YY_DATA_IMG> YY_DATA_IMG { get; set; }
        public virtual DbSet<YY_DATA_LOG> YY_DATA_LOG { get; set; }
        public virtual DbSet<YY_DATA_MANUAL> YY_DATA_MANUAL { get; set; }
        public virtual DbSet<YY_DATA_ONLINE> YY_DATA_ONLINE { get; set; }
        public virtual DbSet<YY_DATA_REM> YY_DATA_REM { get; set; }
        public virtual DbSet<YY_DATA_STATE> YY_DATA_STATE { get; set; }
        public virtual DbSet<YY_DATA_Statistic> YY_DATA_Statistic { get; set; }
        public virtual DbSet<YY_ITEM_TI> YY_ITEM_TI { get; set; }
        public virtual DbSet<YY_ITEMTYPE> YY_ITEMTYPE { get; set; }
        public virtual DbSet<YY_LOG> YY_LOG { get; set; }
        public virtual DbSet<YY_RTU_Basic> YY_RTU_Basic { get; set; }
        public virtual DbSet<YY_RTU_BI> YY_RTU_BI { get; set; }
        public virtual DbSet<YY_RTU_COMMAND> YY_RTU_COMMAND { get; set; }
        public virtual DbSet<YY_RTU_CONFIGDATA> YY_RTU_CONFIGDATA { get; set; }
        public virtual DbSet<YY_RTU_CONFIGITEM> YY_RTU_CONFIGITEM { get; set; }
        public virtual DbSet<YY_RTU_ITEM> YY_RTU_ITEM { get; set; }
        public virtual DbSet<YY_RTU_WATERYIELD> YY_RTU_WATERYIELD { get; set; }
        public virtual DbSet<YY_RTU_WRES> YY_RTU_WRES { get; set; }
        public virtual DbSet<YY_STATE> YY_STATE { get; set; }
        public virtual DbSet<YY_RTU_ITEMCONFIG> YY_RTU_ITEMCONFIG { get; set; }
        public virtual DbSet<View_LocaInfo_YY_RTU_ITEM> View_LocaInfo_YY_RTU_ITEM { get; set; }
        public virtual DbSet<View_YY_RTU_ITEM> View_YY_RTU_ITEM { get; set; }
        public virtual DbSet<View_YY_RTU_ITEM_Alarm> View_YY_RTU_ITEM_Alarm { get; set; }
        public virtual DbSet<View_YY_RTU_ItemType> View_YY_RTU_ItemType { get; set; }
        public virtual DbSet<Image_Tab> Image_Tab { get; set; }
        public virtual DbSet<View_YY_DATA_AUTO> View_YY_DATA_AUTO { get; set; }
        public virtual DbSet<AlarmCondition_Tab> AlarmCondition_Tab { get; set; }
        public virtual DbSet<View_Alarm_LocalInfo_Item> View_Alarm_LocalInfo_Item { get; set; }
        public virtual DbSet<AlarmUser_Tab> AlarmUser_Tab { get; set; }
        public virtual DbSet<AlarmInfo_Tab> AlarmInfo_Tab { get; set; }
        public virtual DbSet<View_AlarmInfo_LocalInfo_Item> View_AlarmInfo_LocalInfo_Item { get; set; }
        public virtual DbSet<YY_HS_DATA_AUTO> YY_HS_DATA_AUTO { get; set; }
    }
}
