//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_LocaInfo_YY_RTU_ITEM
    {
        public long TempID { get; set; }
        public string STCD { get; set; }
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> ItemDecimal { get; set; }
        public Nullable<int> ItemInteger { get; set; }
        public Nullable<bool> PlusOrMinus { get; set; }
        public string Units { get; set; }
        public Nullable<int> ItemIndex { get; set; }
        public string ItemTypeID { get; set; }
        public string ItemType { get; set; }
        public Nullable<int> ItemTypeIndex { get; set; }
    }
}
