//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YY_DATA_IMG
    {
        public string STCD { get; set; }
        public System.DateTime TM { get; set; }
        public Nullable<System.DateTime> DOWNDATE { get; set; }
        public Nullable<int> NFOINDEX { get; set; }
        public byte[] DATAVALUE { get; set; }
        public string INFO { get; set; }
        public Nullable<int> DATATYPE { get; set; }
    }
}
