//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YY_RTU_WRES
    {
        public string STCD { get; set; }
        public int CODE { get; set; }
        public Nullable<int> ADR_ZX { get; set; }
        public Nullable<int> COM_M { get; set; }
        public string ADR_M { get; set; }
        public Nullable<int> PORT_M { get; set; }
        public Nullable<int> COM_B { get; set; }
        public string ADR_B { get; set; }
        public Nullable<int> PORT_B { get; set; }
        public string PhoneNum { get; set; }
        public string SatelliteNum { get; set; }
    }
}
