//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YY_RTU_ITEM
    {
        public string ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public int ItemInteger { get; set; }
        public int ItemDecimal { get; set; }
        public bool PlusOrMinus { get; set; }
        public string Units { get; set; }
    }
}
